### ISSUE TITLE
Auth middleware crashes on invalid tokens

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-node#115]
**Steps to reproduce:**
1. `kamu login https://node.demo.kamu.dev --access-token x`
2. `kamu login --check https://node.demo.kamu.dev`

**Current behavior:**
- CLI itself crashes on `502 Bad Gateway` response (which isn't great)
- The api-server logs also indicate a crash:
```
6: <kamu_adapter_http::middleware::authentication_layer::AuthenticationMiddleware<Svc> as tower_service::Service<http::request::Request<hyper::body::body::Body>>>::call::{{closure}}
5: <kamu_accounts_services::authentication_service_impl::AuthenticationServiceImpl as kamu_accounts::services::authentication_service::AuthenticationService>::account_by_token::{{closure}}
4: kamu_accounts_services::authentication_service_impl::AuthenticationServiceImpl::decode_access_token
          at /rustc/8337ba9189de188e2ed417018af2bf17a57d51ac/library/core/src/str/mod.rs:89:5
3: core::str::slice_error_fail","time":"2024-08-16T23:36:01.078838621Z
2: core::str::slice_error_fail_rt","time":"2024-08-16T23:36:01.078835651Z
          at /rustc/8337ba9189de188e2ed417018af2bf17a57d51ac/library/core/src/panicking.rs:74:14
1: core::panicking::panic_fmt","time":"2024-08-16T23:36:01.078830578Z
          at /rustc/8337ba9189de188e2ed417018af2bf17a57d51ac/library/std/src/panicking.rs:658:5
0: rust_begin_unwind
stack backtrace
byte index 2 is out of bounds of `x`
thread 'tokio-runtime-worker' panicked at /cargo/git/checkouts/kamu-cli-2db697a901e9a060/bf7229b/src/domain/accounts/services/src/authentication_service_impl.rs:117:25
```

**Expectations:**
- Errors are handled gracefully
- Invalid token is rejected as 400 Bad Request

**Comment by sergiimk** [comment]
Was fixed in https://github.com/kamu-data/kamu-cli/pull/779 but didn't auto-close
